Chaybsdv3
terzeu/invites-website pull request #25
Opened 2021-05-29 04:01 UTC by chaybs

push corrigido para DEV.

2021-05-29 04:17 UTC, GabrielAraujoSouz reviewed
Erro ao dar merge !!
![imagem_2021-05-29_011625](https://user-images.githubusercontent.com/54045772/120057699-7c7aba80-c01b-11eb-8fef-4fcb976ddf71.png)

2021-05-29 12:53 UTC, terzeu requested changes
Resolver conflito e os pontos citados

2021-05-29 12:53 UTC, terzeu commented on src/App.vue
> +
Remover espaço

2021-05-29 12:53 UTC, terzeu commented on src/App.vue
> +
remover espaço

2021-05-29 12:53 UTC, terzeu commented on src/App.vue
> +
remover espaço

2021-05-29 12:53 UTC, terzeu commented on src/assets/app.scss
> +// @font-face {
remover linhas comentadas

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +
Colocar nome do componente

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +<template>
Renomear componente para "Header"

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +<header class="cabess">
mudar nome da classe,  vamos evitar usar o português para nomear . "header-component" é um bom nome

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +  justify-content: space-between;
nice!

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +  margin: auto 80px;
retirar o margin auto, use o flexbox para centralizar o conteúdo

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +<style>
utilizar scss

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +body{
esse estyle nao faz parte do componente header

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +ul{
encadear estilos. ex.:
.header-component {
  ul {
    li {
       }
     }
}

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +      <ul>
Nomear uma classe para um componente sempre que quiser mudar o estilo dele

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +         <li>confirmar presença</li>
identar

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +        <a href="localhost:8080"><li>inicio</li></a>
Faria mas sentido inverter o li com o a. Ex:
"{li}{a}{/a}{/li}"

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +        <a href="localhost:8080"><li>inicio</li></a>
Não podemos citar o localhost, isso daria pau quando o site estivesse publicado. Experimente "#" no lugar

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +li{
do jeito que vc escreveu, todas as tags li do projeto receberão esse style

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +ul{
do jeito que vc escreveu, todas as tags ul do projeto receberão esse style

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +nav{
do jeito que vc escreveu, todas as tags nav do projeto receberão esse style

2021-05-29 12:53 UTC, terzeu commented on src/components/Cabeca.vue
> +body{
adicionar espaço depois das "{" sempre

2021-05-29 13:02 UTC, terzeu requested changes

2021-05-29 13:02 UTC, terzeu commented on src/components/Cabeca.vue
> +<template>
Esse PR está fazendo a issue #17 ? se sim: assinar a issue, vincula-la a este PR e move-la para doing

2021-06-03 01:33 UTC, chaybs commented on src/components/Cabeca.vue
> +
nao entendi, é para colocar o nome do próprio componente ?

2021-06-03 01:36 UTC, terzeu commented on src/components/Cabeca.vue
> +
isso, que nem aqui:
![image](https://user-images.githubusercontent.com/56237991/120572788-f2539d00-c3f2-11eb-9110-df0bc3417261.png)

2021-06-03 01:38 UTC, chaybs commented on src/components/Cabeca.vue
> +<template>
feito.

2021-06-03 01:40 UTC, chaybs commented on src/components/Cabeca.vue
> +<header class="cabess">
feito.

2021-06-03 01:43 UTC, chaybs commented on src/components/Cabeca.vue
> +<style>
feito.

2021-06-03 01:43 UTC, chaybs commented on src/components/Cabeca.vue
> +body{
feito.

2021-06-03 02:42 UTC, chaybs commented on src/components/Cabeca.vue
> +ul{
feito.

2021-06-03 02:42 UTC, chaybs commented on src/components/Cabeca.vue
> +      <ul>
feito.

2021-06-03 02:44 UTC, chaybs commented on src/components/Cabeca.vue
> +         <li>confirmar presença</li>
feito.

2021-06-03 02:44 UTC, chaybs commented on src/components/Cabeca.vue
> +        <a href="localhost:8080"><li>inicio</li></a>
feito.

2021-06-03 02:45 UTC, chaybs commented on src/components/Cabeca.vue
> +        <a href="localhost:8080"><li>inicio</li></a>
feito.

2021-06-03 02:45 UTC, chaybs commented on src/components/Cabeca.vue
> +li{
feito.

2021-06-03 02:45 UTC, chaybs commented on src/components/Cabeca.vue
> +ul{
feito.

2021-06-03 02:45 UTC, chaybs commented on src/components/Cabeca.vue
> +nav{
feito.

2021-06-03 02:45 UTC, chaybs commented on src/components/Cabeca.vue
> +body{
feito.

2021-06-03 12:15 UTC, terzeu approved these changes

2021-06-03 22:46 UTC, merged