Location page
terzeu/invites-website pull request #37
Opened 2021-06-10 20:22 UTC by GabrielAraujoSouz

Criando a página de localização dos clientes !!
-Adicionado o awesome icons
-Nova página no site
-Mapa de localização
-Informações do evento

2021-06-10 21:13 UTC, terzeu requested changes
Mandou super bem, o código ficou muito bem escrito.

2021-06-10 21:13 UTC, terzeu commented on src/views/Location.vue
> +    margin:  0px 100px 0px 100px;
isso é a mesma coisa que "0px 100px", desta forma fica mais enxuto

2021-06-10 21:13 UTC, terzeu commented on src/views/Location.vue
> +      flex-direction: row;
o padrão é o direction row, não é necessário essa linha.

2021-06-10 21:13 UTC, terzeu commented on src/views/Location.vue
> +      flex-wrap: wrap;
o flex wrap quebra os conteudos quando não couberem na mesma linha.
Talvez nesse caso vc só queira utilizar o direction column sem o wrap.
Ou talvez nem usar a flexbox

2021-06-11 00:02 UTC, GabrielAraujoSouz reviewed
novo request pós revisão

2021-06-11 00:02 UTC, GabrielGaba commented on src/views/Location.vue
> +    margin:  0px 100px 0px 100px;
feito

2021-06-11 00:02 UTC, GabrielGaba commented on src/views/Location.vue
> +      flex-direction: row;
feito

2021-06-11 00:02 UTC, GabrielGaba commented on src/views/Location.vue
> +      flex-wrap: wrap;
feito

2021-06-11 13:10 UTC, terzeu approved these changes

2021-06-11 13:25 UTC, merged