Chaybsdv5
terzeu/invites-website pull request #38
Opened 2021-06-11 14:01 UTC by chaybs

2021-06-11 15:12 UTC, terzeu requested changes

2021-06-11 15:12 UTC, terzeu commented on src/views/Confirm.vue
> +    color: #fff;
Essa cor está se repetindo em todos os textos, defini-la na classe da página "confirm-presence"

2021-06-11 15:12 UTC, terzeu commented on src/views/Confirm.vue
> +    .sucess {
colocar as classes dos tipos de botão dentro da classe buttons.
Ex:
.buttons {
    &.success {

2021-06-11 15:12 UTC, terzeu commented on src/views/Confirm.vue
> +    .sucess {
escrito errado: success

2021-06-11 15:12 UTC, terzeu commented on src/views/Confirm.vue
> +    background-position: 1 0 0 ;
nao faz sentido, remover

2021-06-11 15:12 UTC, terzeu commented on src/views/Confirm.vue
> +    line-height: 180px;
vc não utilizou flexbox para posicionar o texto, usou o line-height.
Utilize o flex box: Você pode criar uma div pai com a classe banner e colocar o span dentro dela.
Após centralizar o conteúdo com a flexbox utilize um margin-top no span para adequar o texto dentro do banner.

2021-06-11 15:12 UTC, terzeu commented on src/views/Confirm.vue
> +    <h2>confirme sua presença</h2>
o texto está todo em caixa baixa

2021-06-11 15:12 UTC, terzeu commented on src/views/Confirm.vue
> +    <span class="day">quinta feira as 15 horas</span>
o texto está todo em caixa baixa

2021-06-11 15:12 UTC, terzeu commented on src/views/Confirm.vue
> +    <p>Por favor, Selecione uma das 3 opções abaixo:</p>
Selecione -> "selecione"

2021-06-15 16:26 UTC, chaybs commented on src/views/Confirm.vue
> +    color: #fff;
feito.

2021-06-15 16:26 UTC, chaybs commented on src/views/Confirm.vue
> +    .sucess {
feito.

2021-06-15 16:26 UTC, chaybs commented on src/views/Confirm.vue
> +    .sucess {
feito.

2021-06-15 20:22 UTC, terzeu requested changes

2021-06-15 20:22 UTC, terzeu commented on src/views/Confirm.vue
> +      background-color: #07b307;
identado errado

2021-06-15 20:22 UTC, terzeu commented on src/views/Confirm.vue
> +     &.warning {
fazer o mesmo que vc fez para o success

2021-06-15 20:22 UTC, terzeu commented on src/views/Confirm.vue
> +    &.danger {
fazer o mesmo que vc fez para o success

2021-06-15 20:22 UTC, terzeu commented on src/views/Confirm.vue
> +    flex-direction: column;
Não precisa dessa linha

2021-06-15 20:22 UTC, terzeu commented on src/views/Confirm.vue
> +    justify-content: center;
use o align-items: center também

2021-06-15 20:26 UTC, terzeu requested changes

2021-06-15 20:26 UTC, terzeu commented on src/views/Confirm.vue
> +  name: 'Confirm'
Que tal mudar o nome da pagina para Presence ?
Acho que ela tem mais a ver com presença do que confirmação, socou ?

2021-06-15 21:36 UTC, terzeu approved these changes

2021-06-15 21:36 UTC, merged