header ajustado em javascript
terzeu/invites-website pull request #54
Opened 2021-06-25 22:28 UTC by chaybs

2021-06-28 15:32 UTC, terzeu requested changes

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +      </ul>
remover espaço a mais depois do </ul>

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +      return;
esse return não é necessário

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +        return;
em vez de utilizar esse return use o design pattern de if/else

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +    justify-content: center;
Voce está alinhando os itens dando margin. O justify-content: center; só era pra ser definido quando a tela fosse "mobile".

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +      margin-right: 150px;
remover

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +    @media (max-width: 750px) {
você tem uma variavel js para identificar se a tela é mobile.
utilize:
       :class="{mobile: mobile}"
para criar uma classe css, a partir dessa classe que vc definirá os estilos abaixo.
Resumindo... substituir o @media por uma classe css "mobile"

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +      display: flex;
remover, não faz sentido, esse elento só tem 1 filho

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +      justify-content: initial;
remover, não faz sentido, esse elento só tem 1 filho

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +        display: flex;
use display block

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +
remover linha

2021-06-28 15:32 UTC, terzeu commented on src/components/Header.vue
> +        margin: auto;
remover

2021-06-28 15:32 UTC, terzeu commented on src/views/Home.vue
> +  height: 100%;
vc e o gabinha precisam se resolver, é 100vh ou 100% ?
acredito ser 100vh

2021-06-29 20:05 UTC, chaybs commented on src/views/Home.vue
> +  height: 100%;
isso será resolvido em uma issue futura de responsividade.

2021-06-30 22:27 UTC, terzeu approved these changes

2021-06-30 22:27 UTC, terzeu commented on src/components/Header.vue
> +  <header :class="{ 'mobile': mobile}" class="header-component">
faltando um espaço depois de mobile

2021-06-30 22:27 UTC, terzeu commented on src/components/Header.vue
> +    window.addEventListener('resize' , this.checkScreen);
remover ";"

2021-06-30 22:27 UTC, terzeu commented on src/components/Header.vue
> +    this.checkScreen();
remover ";"

2021-06-30 22:27 UTC, terzeu commented on src/components/Header.vue
> +      },
identado errado

2021-06-30 22:27 UTC, terzeu commented on src/components/Header.vue
> +.mobile {
usar:
 .mobile {
               &.header-component {

2021-07-01 02:02 UTC, merged